ansible_ssh_user: ansible_user
#ansible_ssh_private_key_file: /home/ubuntu/PlayBook/PB4/ansible-webapp/ansible_agent1.pub
#ansible_ssh_password: "{{ vault_ansible_password }}"
#ansible_sudo_pass: "{{ ansible_sudo_pass }}"
#vault_encrypt_identity: "{{ vault_encrypt_identity }}"
