- name: "Git Clone And Push to GitHub Repositories"
  hosts: prod
  #pre_tasks:
   # - name: "Initialisation"
  tasks:
    - name: "Clone GIT Repository"
      ansible.builtin.git:
        repo: "{{ src_repo }}"
        dest: "{{ tmp_repo_directory }}"
        clone: yes
        update: yes
    - name: "Copy New Files"
      copy:
        dest: "{{ tmp_repo_directory }}"
        src: "{{ item }}"
        force: true
      loop:
        - "{{ source_dir }}/PB1/"
        - "{{ source_dir }}/PB2/"
    - name: "Add output directory to git"
      ansible.builtin.shell: |
        git config --global user.name "grethoremas3333"
        git config --global user.email "grethoremas@gmail.com"
        git config --global user.password "4Zc./47dRo;4"
        git config --global user.token "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"
        git add .
        git commit -m "Update Files {{ tower_job_id }}: Automated Commit by Ansible"
        git push https://"{{GIT_TOKEN}}"@github.com/grethoremas3333/ansible-webapp.git
      args:
        chdir: "{{ tmp_repo_directory }}"
  vars:
    src_repo: https://github.com/grethoremas3333/ansible-webapp.git
    dest_repo: https://github.com/grethoremas3333/ansible-webapp.git
    dest_branch: main
    tmp_repo_directory: /home/ansible_agent_un/GIT
    source_dir: /home/ansible_server/PlayBook
    tower_job_id: v1.0.0
    GIT_USER_NAME: grethoremas3333
    GIT_PASSWORD: 4Zc./47dRo;4
    GIT_TOKEN: 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
