- name: "deploiement role WordPress"
  hosts: prod
  become: true
  vars:
    system_user: ansible_user
  vars_files:
    - files/secrets/credentials.yml
  pre_tasks:
    - name: "Creer utilisateur www-data"
      user: name=www-data state=present
  roles:
    - { role: ansible-role-containerized-wordpress }
